---
title: "`rrr` for Canonical Variate Analysis"
author: "Chris Addy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
 
```{r}
set.seed(12345)
```

## Mathematical Background

## The `COMBO17` Data Set

```{r}
### COMBO-17 galaxy data
data(COMBO17)
galaxy <- as_data_frame(COMBO17) %>%
       select(-starts_with("e."), -Nr, -UFS:-IFD) %>%
       na.omit()

#glimpse(galaxy)
```

```{r}
galaxy_x <- galaxy %>%
	select(-Rmag:-chi2red)

galaxy_y <- galaxy %>%
	select(Rmag:chi2red)
```

```{r}
GGally::ggcorr(galaxy_x)
```

```{r}
GGally::ggcorr(galaxy_y)
```

## Assessing Effective Dimensionality

### Estimate $t$ and $k$ with `cva_rank_trace()` and `cva_rank_trace_plot()`

```{r}
cva_rank_trace(galaxy_x, galaxy_y)
```

```{r}
cva_rank_trace_plot(galaxy_x, galaxy_y)
```

```{r}
args(cva_error)
```

```{r}
### create training and test sets

num_obs <- dim(galaxy)[1]
train_number <- floor(.75 * num_obs)
train_index <- sample(num_obs, train_number)

### training set
train_galaxy_x <- galaxy_x[train_index, ]
train_galaxy_y <- galaxy_y[train_index, ]

### test set
test_galaxy_x <- galaxy_x[-train_index, ]
test_galaxy_y <- galaxy_y[-train_index, ]
```

```{r, echo = FALSE}
train <- function(rank, k){
	cva_error(train_galaxy_x, train_galaxy_y, test_galaxy_x, test_galaxy_y, rank, type = "cov", k)
}
```

## Diagnostics

```{r}
#cva_residual_plot(galaxy_x, galaxy_y, rank = 2, k = 0.001)
```

```{r}
cv_pairwise_plot(galaxy_x, galaxy_y, cv_pair = 1, k = 0.0001)

cv_pairwise_plot(galaxy_x, galaxy_y, cv_pair = 2, k = 0.0001)
```

```{r}
rrcva(galaxy_x, galaxy_y, rank = 2, k = 0.0001)
```