---
title: "`rrr` for Multivariate Analysis"
author: "Chris Addy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(rrr)
```

## Principle Components Analysis 

```{r message = FALSE, warning = FALSE}

library(dplyr)

data(pendigits)
digits <- as_data_frame(pendigits)

digits_class <- digits %>% dplyr::select(V35)
digits_features <- digits %>% dplyr::select(-V5, -V6)

digits_pca <- rrpca(digits_features)

pca_gof(digits_features) %>% round(4)

pca_rank_trace(digits_features)

pca_rank_trace_plot(digits_features)

pc_pairwise_plot(digits_features, class_labels = digits_class)


#pc_plot_3D(digits_features, class_labels = digits_class)
```

## Canonical Variate Analysis

```{r}
### COMBO-17 galaxy data
#data(COMBO17)
#galaxy <- as_data_frame(COMBO17) %>%
#       select(-starts_with("e."), -Nr, -UFS:-IFD) %>%
#       na.omit()

#galaxy_x <- galaxy %>% select(-Rmag:-chi2red)
#galaxy_y <- galaxy %>% select(Rmag:chi2red)

#galaxy_x
#galaxy_y

#rrcva(galaxy_x, galaxy_y, rank = 2)
```

## Linear Discriminant Analysis
